### ISSUE TITLE
GET /minions not found

### ISSUE THREAD

**Issue by countspongebob** [kubernetes-ui/kubernetes#2]
Bobs-MBP:app bob$ kubectl get minions
NAME                LABELS              STATUS
172.16.1.102        <none>              Ready
172.16.1.103        <none>              Ready

Bobs-MBP:app bob$ http-server -a localhost -p 8000
Starting up http-server, serving ./ on: http://localhost:8000
Hit CTRL-C to stop the server
[Tue, 24 Mar 2015 19:06:06 GMT] "GET /minions" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36"
[Tue, 24 Mar 2015 19:06:06 GMT] "GET /minions" Error (404): "Not found"
[Tue, 24 Mar 2015 19:06:09 GMT] "GET /minions" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36"
[Tue, 24 Mar 2015 19:06:09 GMT] "GET /minions" Error (404): "Not found"
[Tue, 24 Mar 2015 19:06:12 GMT] "GET /minions" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36"
[Tue, 24 Mar 2015 19:06:12 GMT] "GET /minions" Error (404): "Not found"

(and I hit ctrl-c to stop)

**Comment by preillyme** [comment]
@countspongebob — My understanding was that we were having a call today to help with the set-up.
Is that no longer the case?

**Comment by preillyme** [comment]
@countspongebob — It looks like you're missing some settings in your ```development.json``` can you post the content of that file?

**Comment by preillyme** [comment]
Have you renamed https://github.com/kubernetes-ui/kubernetes/blob/kubernetes-ui/www/master/shared/config/development.example.json to ```development.json``` and changed your settings to match your cluster?

**Comment by bcbroussard** [comment]
@countspongebob I think this could be a `development.json` settings issue as well. In case it is unclear, the `k8sApiServer` value should point to the kubernetes master node.

**Comment by bcbroussard** [comment]
@countspongebob thanks for testing this out with us. It's great to have a fresh set of eyes to help close any gaps in documentation.

**Comment by countspongebob** [comment]
{
  "k8sApiServer": "http://172.16.1.101:8001/api/v1beta2",
  "k8sDataServer": "http://172.16.1.101:5555/cluster",
  "k8sDataPollMinIntervalSec": 10,
  "k8sDataPollMaxIntervalSec": 120,
  "k8sDataPollErrorThreshold": 5,
  "cAdvisorProxy": "http://172.16.1.101/proxy?TARGET=",
  "cAdvisorPort": "4194"
}

**Comment by bcbroussard** [comment]
# Instructions to install web UI chrome and dashboard

The kubernetes web ui is now split out into a base chrome project, and multiple dashboards. At least 1 dashboard needs to be installed. These are temporary instructions for testing locally before we finalize the dashboard.

To Install Kubernetes Dashboard
```
cd www/master/components
```
Copy the dashboard repo
```
git clone git@github.com:kubernetes-ui/dashboard.git www/master/components/dashboard
```

To Install Graph Visualization Dashboard
```
cd www/master/components
```
Copy the graph repo
```
git clone git@github.com:kubernetes-ui/graph.git www/master/components/graph
```

Then continue with normal installation instructions in detailed in [www/README.md](https://github.com/kubernetes-ui/kubernetes/blob/kubernetes-ui/www/README.md) to:
 - setup your `development.json`
 - run npm start

If you see the javascript error `componentNamespaces is not defined` the first time you run it, retry `npm start` and also restart the web server

**Comment by countspongebob** [comment]
Final resolution was to get the install/run procedure detailed to where it wasn't (my) pilot error causing issues. See https://github.com/kubernetes-ui/kubernetes/wiki/An-example-of-running-the-UI
